// Code generated by "stringer -type ExternalKind -trimprefix ExtKind"; DO NOT EDIT.

package wasm

import "strconv"

const _ExternalKind_name = "FunctionTableMemoryGlobal"

var _ExternalKind_index = [...]uint8{0, 8, 13, 19, 25}

func (i ExternalKind) String() string {
	if i >= ExternalKind(len(_ExternalKind_index)-1) {
		return "ExternalKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExternalKind_name[_ExternalKind_index[i]:_ExternalKind_index[i+1]]
}
