// Code generated by "stringer -type LanguageType -trimprefix LanguageType_"; DO NOT EDIT.

package wasm

import "strconv"

const (
	_LanguageType_name_0 = "block"
	_LanguageType_name_1 = "func"
	_LanguageType_name_2 = "anyfunc"
	_LanguageType_name_3 = "f64f32i64i32"
)

var (
	_LanguageType_index_3 = [...]uint8{0, 3, 6, 9, 12}
)

func (i LanguageType) String() string {
	switch {
	case i == 64:
		return _LanguageType_name_0
	case i == 96:
		return _LanguageType_name_1
	case i == 112:
		return _LanguageType_name_2
	case 124 <= i && i <= 127:
		i -= 124
		return _LanguageType_name_3[_LanguageType_index_3[i]:_LanguageType_index_3[i+1]]
	default:
		return "LanguageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
