// Code generated by "stringer -type LangType -trimprefix LangType"; DO NOT EDIT.

package wasm

import "strconv"

const (
	_LangType_name_0 = "Block"
	_LangType_name_1 = "Func"
	_LangType_name_2 = "AnyFunc"
	_LangType_name_3 = "Float64Float32Int64Int32"
)

var (
	_LangType_index_3 = [...]uint8{0, 7, 14, 19, 24}
)

func (i LangType) String() string {
	switch {
	case i == 64:
		return _LangType_name_0
	case i == 96:
		return _LangType_name_1
	case i == 112:
		return _LangType_name_2
	case 124 <= i && i <= 127:
		i -= 124
		return _LangType_name_3[_LangType_index_3[i]:_LangType_index_3[i+1]]
	default:
		return "LangType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
