// Code generated by "stringer -type NameType -trimprefix NameType"; DO NOT EDIT.

package wasm

import "strconv"

const _NameType_name = "ModuleFunctionLocal"

var _NameType_index = [...]uint8{0, 6, 14, 19}

func (i NameType) String() string {
	if i < 0 || i >= NameType(len(_NameType_index)-1) {
		return "NameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NameType_name[_NameType_index[i]:_NameType_index[i+1]]
}
