// Code generated by "stringer -type OpCode -trimprefix Op"; DO NOT EDIT.

package wasm

import "strconv"

const (
	_OpCode_name_0 = "Block"
	_OpCode_name_1 = "Func"
	_OpCode_name_2 = "AnyFunc"
	_OpCode_name_3 = "Float64Float32Int64Int32"
)

var (
	_OpCode_index_3 = [...]uint8{0, 7, 14, 19, 24}
)

func (i OpCode) String() string {
	switch {
	case i == 64:
		return _OpCode_name_0
	case i == 96:
		return _OpCode_name_1
	case i == 112:
		return _OpCode_name_2
	case 124 <= i && i <= 127:
		i -= 124
		return _OpCode_name_3[_OpCode_index_3[i]:_OpCode_index_3[i+1]]
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
