// Code generated by "stringer -type ValueType -trimprefix ValueType_"; DO NOT EDIT.

package wasm

import "strconv"

const _ValueType_name = "f64f32i64i32"

var _ValueType_index = [...]uint8{0, 3, 6, 9, 12}

func (i ValueType) String() string {
	i -= 124
	if i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i+124), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
